import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { bodyW } from "@/app/variables/variables";
import Anchor from "./components/NavAnchor";
import FadeInOnLoad from "./components/FadeInOnLoad";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
          <Navbar />
          <div
            className={`${bodyW} mx-auto flex justify-center my-24`}>
              <FadeInOnLoad><Anchor text="body" /></FadeInOnLoad>
          </div>
          {children}
      </body>
    </html>
  );
}
