import type { Metadata } from "next";
import { Oswald, Poppins } from "next/font/google";
import "./globals.css";


const oswald = Oswald({
  variable: "--font-oswald-variable",
  subsets: ['latin']
})

const poppins = Poppins({
  weight: ["500", "700"],
  variable: "--font-poppins-variable",
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${poppins.variable} antialiased make-me-fit-body`}
      >
        
        <main>{children}</main>
      </body>
    </html>
  );
}
